/*
 * File: app/store/TrainLineStopsStore.js
 *
 * This file was generated by Sencha Architect version 3.5.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('TrainTrax.store.TrainLineStopsStore', {
    extend: 'Ext.data.Store',

    requires: [
        'Ext.data.Field',
        'Ext.data.proxy.Ajax',
        'Ext.data.reader.Array'
    ],

    config: {
        storeId: 'TrainLineStopsStore',
        fields: [
            {
                name: 'direction_id'
            },
            {
                name: 'location'
            },
            {
                name: 'map_id'
            },
            {
                name: 'station_descriptive_name'
            },
            {
                name: 'station_name'
            },
            {
                name: 'stop_id'
            },
            {
                name: 'stop_name'
            }
        ],
        proxy: {
            type: 'ajax',
            reader: {
                type: 'array'
            }
        }
    }
});