/*
 * File: app/view/Lines.js
 *
 * This file was generated by Sencha Architect version 3.5.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('TrainTrax.view.Lines', {
    extend: 'Ext.Panel',
    alias: 'widget.lines',

    requires: [
        'Ext.Toolbar',
        'Ext.dataview.List',
        'Ext.XTemplate'
    ],

    config: {
        layout: 'fit',
        items: [
            {
                xtype: 'toolbar',
                docked: 'top',
                title: 'Train Trax'
            },
            {
                xtype: 'list',
                itemId: 'trainLineList',
                itemCls: 'tt_lineListItem',
                itemTpl: [
                    '<div class="tt_lineListItemInner" style="color:#{RouteTextColor}; background-color:#{RouteColorCode};">{Route} <i class="fa fa-exclamation-triangle" style="float:right;"></i></div>'
                ],
                store: 'TrainLineStore'
            }
        ],
        listeners: [
            {
                fn: 'onTrainLineListSelect',
                event: 'select',
                delegate: '#trainLineList'
            }
        ]
    },

    onTrainLineListSelect: function(dataview, record, eOpts) {
        AERP.Ajax.request({
            url:'getStationsOfLine',
            params:{lineId:record.get('ServiceId')},
            success:function(reply){
                Ext.ComponentQuery.query('#cardsScreen')[0].setActiveItem('#stopsOnLineScreen');
                Ext.ComponentQuery.query('#stopsTitlebar')[0].setStyle('background:#'+record.get('RouteColorCode')+';');
                var bar = Ext.ComponentQuery.query('#stopsTitlebar')[0].setTitle('<span style="text-shadow:none; color:#'+record.get('RouteTextColor')+';">'+record.get('Route')+'</span>');
            }
        });



    }

});