/*
 * File: app/view/StopsOnLine.js
 *
 * This file was generated by Sencha Architect version 3.5.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('TrainTrax.view.StopsOnLine', {
    extend: 'Ext.Panel',
    alias: 'widget.stopsonline',

    requires: [
        'Ext.Toolbar',
        'Ext.Button',
        'Ext.dataview.List',
        'Ext.XTemplate'
    ],

    config: {
        layout: 'fit',
        items: [
            {
                xtype: 'toolbar',
                docked: 'top',
                itemId: 'stopsTitlebar',
                title: '[Line Name]',
                items: [
                    {
                        xtype: 'button',
                        itemId: 'mybutton',
                        ui: 'back',
                        text: 'Back'
                    }
                ]
            },
            {
                xtype: 'list',
                itemTpl: [
                    '<div>List Item {string}</div>'
                ]
            }
        ],
        listeners: [
            {
                fn: 'onMybuttonTap',
                event: 'tap',
                delegate: '#mybutton'
            }
        ]
    },

    onMybuttonTap: function(button, e, eOpts) {
        Ext.ComponentQuery.query('#cardsScreen')[0].setActiveItem('#linesScreen');
    }

});