/*
 * File: app/store/TrainLineStore.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('TrainTrax.store.TrainLineStore', {
	extend: 'Ext.data.Store',

	requires: [
		'Ext.data.Field',
		'Ext.data.proxy.Ajax',
		'Ext.data.reader.Array'
	],

	config: {
		storeId: 'TrainLineStore',
		fields: [
			{
				name: 'Route'
			},
			{
				name: 'RouteColorCode'
			},
			{
				name: 'RouteTextColor'
			},
			{
				name: 'ServiceId'
			},
			{
				name: 'RouteURL'
			},
			{
				name: 'RouteStatus'
			},
			{
				name: 'RouteStatusColor'
			},
			{
				name: 'NiceName'
			}
		],
		proxy: {
			type: 'ajax',
			reader: {
				type: 'array'
			}
		}
	}
});